### ISSUE TITLE
Indicate that this repo is not up to date (point to linas' version instead)

### ISSUE THREAD

**Issue by oskarb** [goedson/gnotime#5]
A more up-to-date github repo for gnotime (contains commits for 2.4.1, and more) is at https://github.com/linas/gnotime. Unfortunately they are not linked as forks on github.

**Comment by oskarb** [comment]
For anyone interested, there are currently a lot of modernization work done in another fork: https://github.com/markuspg/gnotime/tree/modernize3

**Comment by linas** [comment]
See discussion in pull req #3

**Comment by goedson** [comment]
I pulled the missing commits from Linas's master branch, including the updates to the README with links to Markus's and GnoTime/gnotime repositories.
